image: docker:19.03.1

 # Pinning the right Docker version for the service also
services:
  - docker:19.03.1-dind

variables:
  DOCKER_DRIVER: overlay2
  DATABASE_URL: 'mongodb://mongo/user_posts'

# image: docker:stable-dind


stages:
  - build
  - test
  - review
  - stage
  - production

before_script:
#  - apt-get update && apt-get install -y ruby-full ruby-bundler build-essential
  - docker login -u $HUB_LOGIN -p $HUB_PASSWORD
  - docker info
  # - cd reddit
  # - bundle install

build_job:
  #image: docker:19.03.1-dind
  stage: build
  #before_script:
  #  - echo 'Getting, building and publishing docker-monolith'
  script:
    - docker info
    - ls -l
   # - cd ./docker-monolith
   # - ls -l
    - cd ./reddit
    - docker info
    - docker build -t reddit:latest .
    - docker images -a
   # - docker login -u $HUB_LOGIN -p $HUB_PASSWORD
    - docker tag reddit:latest $HUB_LOGIN/otus-reddit:3.$CI_PIPELINE_ID
    - docker push $HUB_LOGIN/otus-reddit:3.$CI_PIPELINE_ID
    - docker rmi reddit

test_unit_job:
  image: ruby:2.4.2
  stage: test
  services:
    - mongo:latest
  script:
    - cd reddit
    - bundle install
    - ruby simpletest.rb
    - echo 'Unit tests'

test_integration_job:
  stage: test
  script:
    - echo 'Integration tests'

deploy_dev_job:
  stage: review
  script:
    - echo 'Deploy'
    # - docker login -u $HUB_LOGIN -p $HUB_PASSWORD
    - docker inspect $HUB_LOGIN/otus-reddit:3.$CI_PIPELINE_ID
    #- if docker ps -a | grep reddit; then docker stop reddit && docker rm reddit; fi
    #- docker run --name reddit -d -p 9292:9292 $HUB_LOGIN/otus-reddit:2.$CI_PIPELINE_ID
  environment:
    name: dev
    url: http://dev.example.com

branch review:
  stage: review
  script: echo "Deploy to $CI_ENVIRONMENT_SLUG"
  environment:
    name: branch/$CI_COMMIT_REF_NAME
    url: http://$CI_ENVIRONMENT_SLUG.example.com
  only:
    - branches
  except:
    - master

staging:
  stage: stage
  when: manual
  only:
    - /^\d+\.\d+\.\d+/
  script:
    - echo 'Deploy'
  environment:
    name: stage
    url: http://beta.example.com

production:
  stage: production
  when: manual
  only:
    - /^\d+\.\d+\.\d+/
  script:
    - echo 'Deploy'
  environment:
    name: production
    url: http://example.com
