# image: docker:stable-dind
image: ruby:2.4.2

stages:
  - build
  - test
  - review
  - stage
  - production

variables:
  DATABASE_URL: 'mongodb://mongo/user_posts'

before_script:
  - cd reddit
  - bundle install

build_job:
  image: docker:19.03.1-dind
  stage: build
  before_script:
    - echo 'Getting, building and publishing reddit'
    # - sudo apt update && install git -y
  script:
    - docker info
    - git clone -b gitlab-ci-1 http://35.246.234.248/homework/example.git
    - ls -l
    - cd ./docker-monolith
    - ls -l
    - docker info
    - docker build -t reddit:latest .
    - docker images -a
    - docker login -u $HUB_LOGIN -p $HUB_PASSWORD
    - docker tag reddit:latest $HUB_LOGIN/otus-reddit:2.$CI_JOB_ID
    - docker push $HUB_LOGIN/otus-reddit:2.$CI_JOB_ID
    - docker rmi reddit

test_unit_job:
  stage: test
  services:
    - mongo:latest
  script:
    - ruby simpletest.rb
    # - echo 'Testing ruby.rb'

test_integration_job:
  stage: test
  script:
    - echo 'Testing 2'

deploy_dev_job:
  stage: review
  script:
    - echo 'Deploy'
    - docker login -u $HUB_LOGIN -p $HUB_PASSWORD
    - docker inspect $HUB_LOGIN/otus-reddit:latest
  environment:
    name: dev
    url: http://dev.example.com

branch review:
  stage: review
  script: echo "Deploy to $CI_ENVIRONMENT_SLUG"
  environment:
    name: branch/$CI_COMMIT_REF_NAME
    url: http://$CI_ENVIRONMENT_SLUG.example.com
  only:
    - branches
  except:
    - master

staging:
  stage: stage
  when: manual
  only:
    - /^\d+\.\d+\.\d+/
  script:
    - echo 'Deploy'
  environment:
    name: stage
    url: http://beta.example.com

production:
  stage: production
  when: manual
  only:
    - /^\d+\.\d+\.\d+/
  script:
    - echo 'Deploy'
  environment:
    name: production
    url: http://example.com
