global:
  slack_api_url: 'https://hooks.slack.com/services/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'

route:
  receiver: 'slack-notifications'

receivers:
- name: 'slack-notifications'
  slack_configs:
  - channel: '#vladimir_deribin'
