global:
  slack_api_url: 'https://hooks.slack.com/services/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'

  smtp_smarthost: 'mailhost:25'
  smtp_from: 'alertmanager@docker-host'
  smtp_auth_username: 'alertmanager'
  smtp_auth_password: 'password'
  smtp_require_tls: false

route:
  receiver: 'slack-notifications'
  routes:
    - match:
        severity: critical
      receiver: 'slack-notifications'
    - match:
        severity: page
      receiver: 'mail-notifications'

receivers:
- name: 'slack-notifications'
  slack_configs:
  - channel: '#vladimir_deribin'

- name: 'mail-notifications'
  email_configs:
  - to: 'appuser@docker-host'
