plugin: gcp_compute
projects:
  - docker-267019
  #- versatile-hull-262415
zones:
  - europe-west3-a
auth_kind: serviceaccount
service_account_file: /builds/homework/example/serviceacc.json
#service_account_file: ~/.config/gcloud/docker-267019-serviceaccount.json
#service_account_file: ~/.config/gcloud/versatile-hull-262415-serviceaccount.json
groups:
  app: "'docker-host' in name"
  # "'docker-host' in (tags['items']|list)"
  # also we can use labels from instances if we will difene them using terraform
  # look all values an ansible-inventory --list
hostnames:
  # List host by name instead of the default public ip
  - name
compose:
  # Set an inventory parameter to use the Public IP address to connect to the host
  # For Private ip use "networkInterfaces[0].networkIP"
  ansible_host: networkInterfaces[0].accessConfigs[0].natIP
  ansible_internal_ip: networkInterfaces[0].networkIP
