version: '3.3'
services:
  post_db:
    image: mongo:${VER_DB}
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}
    volumes:
      - post_db:/data/db
    networks:
      back_net:
        aliases:
          - post_db
          - comment_db
  ui:
    image: ${USERNAME}/ui:${VER_UI}
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: service.ui
    ports:
      - ${PORT_INT}:${PORT_EXT}/tcp
    networks:
      - front_net

  post:
    image: ${USERNAME}/post:${VER_POST}
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: service.post
    networks:
      - front_net
      - back_net

  comment:
    image: ${USERNAME}/comment:${VER_COMMENT}
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}
    networks:
      - front_net
      - back_net

volumes:
  post_db:

networks:
  front_net:
#    external: true
    ipam:
      config:
        - subnet: 10.0.1.0/24
  back_net:
#    external: true
    ipam:
      config:
        - subnet: 10.0.2.0/24
