---
# https://docs.docker.com/install/linux/docker-ce/ubuntu/
- name: Prepare docker-host for packer
  hosts: all
  become: yes
  tasks:

  - name: Install packages to allow https for repos
    apt:
      name: ['apt-transport-https', 'ca-certificates', 'curl', 'gnupg2' ,'software-properties-common']
      state: present
      install_recommend: yes
      update_cache: yes

  - name: Add Docker GPG key
    apt_key: url=https://download.docker.com/linux/ubuntu/gpg
      state: present

  - name: Add Docker APT repository
    apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable
      state: present
      update_cache: yes

  - name: Install Docker
    apt:
      name: ['docker-ce', 'docker-ce-cli', 'containerd.io']
      install_recommends: yes
      update_cache: yes

  - name: Add docker group
    group:
      name: docker
      state: present

  - name: Add appuser to docker group
    user:
      name: appuser
      groups: docker
      append: yes

  # https://success.docker.com/article/how-do-i-enable-the-remote-api-for-dockerd
  - name: Create directory for docker override config, if it does not exist
    file:
      path: /etc/systemd/system/docker.service.d
      state: directory
      # mode: '0755'

  - name: Add override config to set docker listen on 2376 port
    copy:
      src: files/dockeroverride.conf
      dest: /etc/systemd/system/docker.service.d/dockeroverride.conf

  - name: Configure Docker to start on boot
    systemd: name=docker enabled=yes

  - name: restart docker and issue daemon-reload to pick up config changes
    systemd:
      state: restarted
      daemon_reload: yes
      name: docker

#  - name: Pull our reddit image
#    docker_image:
#      name: deribinvladimir/otus-reddit:1.0
#      source: pull
