groups:
  - name: alert.rules
    rules:
    - alert: InstanceDown
      expr: up == 0		# any PromQL request
      for: 1m			# during what time (0 by default)
      labels:			# additional labels
        severity: page
      annotations:
        description: '{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 1 minute'
        summary: 'Instance {{ $labels.instance }} down'
