kind: EncryptionConfig
apiVersion: v1
resources:
  - resources:
      - secrets
    providers:
      - aescbc:
          keys:
            - name: key1
              secret: LcdMBM5/fIatB5kt+uIW2ntCjbXITp7Mway+iQOHpNU=
      - identity: {}
