version: '3.3'
services:
  post_db:
    image: mongo:${VER_DB}
    volumes:
      - post_db:/data/db
    networks:
      - back_net
  ui:
    build: ./ui
    image: ${USERNAME}/ui:${VER_UI}
    ports:
      - ${PORT_INT}:${PORT_EXT}/tcp
    networks:
      - front_net
  post:
    build: ./post-py
    image: ${USERNAME}/post:${VER_POST}
    networks:
      - front_net
      - back_net
  comment:
    build: ./comment
    image: ${USERNAME}/comment:${VER_COMMENT}
    networks:
      - front_net
      - back_net

volumes:
  post_db:

networks:
  front_net:
    external: true
  back_net:
    external: true
